pipeline:
  # integration:
  #   image: python:2
  #   commands:
  #     - echo "Building"

  delivery:
    image: plugins/docker
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    repo: "${DOCKER_REPO}"
    tag: "${DRONE_BRANCH##feature/}"

  deliveryprod:
    image: plugins/docker
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    tag: latest
    when:
      branch: master

  notify:
    image: hpreston/drone-spark:0.7
    secrets: [ SPARK_TOKEN, PERSONEMAIL ]
    message: "Build Complete!"
    when:
      status: [ success, failure ]
